"""empty message

Revision ID: a4bc433be502
Revises: a5cffa318ac2
Create Date: 2024-07-17 16:18:18.325044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bc433be502'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=250), nullable=False),
    sa.Column('character_height', sa.Integer(), nullable=True),
    sa.Column('character_mass', sa.Integer(), nullable=True),
    sa.Column('character_hair_color', sa.String(length=250), nullable=True),
    sa.Column('character_skin_color', sa.String(length=250), nullable=True),
    sa.Column('character_eye_color', sa.String(length=250), nullable=True),
    sa.Column('character_birth_year', sa.String(length=250), nullable=True),
    sa.Column('character_gender', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(length=250), nullable=False),
    sa.Column('planet_rotation_period', sa.Integer(), nullable=True),
    sa.Column('planet_orbital_period', sa.Integer(), nullable=True),
    sa.Column('planet_diameter', sa.Integer(), nullable=True),
    sa.Column('planet_climate', sa.String(length=250), nullable=True),
    sa.Column('planet_terrain', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_model', sa.String(length=250), nullable=False),
    sa.Column('vehicle_cost', sa.Integer(), nullable=True),
    sa.Column('vehicle_max_speed', sa.Integer(), nullable=True),
    sa.Column('vehicle_crew', sa.Integer(), nullable=True),
    sa.Column('vehicle_passengers', sa.Integer(), nullable=True),
    sa.Column('vehicle_cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('vehicle_consumables', sa.Integer(), nullable=True),
    sa.Column('vehicle_hyperdrive_rating', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=25), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    op.drop_table('favorites')
    op.drop_table('vehicle')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
