"""empty message

Revision ID: be5f03854771
Revises: a4bc433be502
Create Date: 2024-07-22 18:53:00.595617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5f03854771'
down_revision = 'a4bc433be502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=250), nullable=True))
        batch_op.drop_column('character_height')
        batch_op.drop_column('character_hair_color')
        batch_op.drop_column('character_mass')
        batch_op.drop_column('character_birth_year')
        batch_op.drop_column('character_gender')
        batch_op.drop_column('character_eye_color')
        batch_op.drop_column('character_name')
        batch_op.drop_column('character_skin_color')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_speed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('crew', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passengers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cargo_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('consumables', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hyperdrive_rating', sa.String(length=250), nullable=True))
        batch_op.drop_column('vehicle_hyperdrive_rating')
        batch_op.drop_column('vehicle_consumables')
        batch_op.drop_column('vehicle_model')
        batch_op.drop_column('vehicle_max_speed')
        batch_op.drop_column('vehicle_passengers')
        batch_op.drop_column('vehicle_cost')
        batch_op.drop_column('vehicle_cargo_capacity')
        batch_op.drop_column('vehicle_crew')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_crew', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_cargo_capacity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_cost', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_passengers', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_max_speed', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_model', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vehicle_consumables', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_hyperdrive_rating', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('hyperdrive_rating')
        batch_op.drop_column('consumables')
        batch_op.drop_column('cargo_capacity')
        batch_op.drop_column('passengers')
        batch_op.drop_column('crew')
        batch_op.drop_column('max_speed')
        batch_op.drop_column('cost')
        batch_op.drop_column('model')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_skin_color', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('character_eye_color', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_gender', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_birth_year', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_mass', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_hair_color', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_height', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
