"""empty message

Revision ID: f393011ab698
Revises: be5f03854771
Create Date: 2024-07-22 20:28:38.558256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f393011ab698'
down_revision = 'be5f03854771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('climate', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.String(length=250), nullable=True))
        batch_op.drop_column('planet_orbital_period')
        batch_op.drop_column('planet_climate')
        batch_op.drop_column('planet_rotation_period')
        batch_op.drop_column('planet_diameter')
        batch_op.drop_column('planet_name')
        batch_op.drop_column('planet_terrain')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_terrain', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('planet_diameter', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_rotation_period', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_climate', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_orbital_period', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')
        batch_op.drop_column('diameter')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
